# .rubocop.yml
#
# Configuration for rubocop, a static code analyzer for Ruby.
#
# https://github.com/bbatsov/rubocop#configuration

inherit_from: .rubocop_todo.yml

# Disable documentation checks.
Documentation:
  Enabled: false

# Disable module length cop.
Metrics/ModuleLength:
  Enabled: false

# Set enforced hash syntax style to hash rockets.
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Disable %w / %W array of words warning.
#
# Disable this cop because it encourages mixing array styles.
#
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
Style/WordArray:
  MinSize: 5
